SPOI-9079 Added sample application for transform operator
DataTorrent/examples pull request #32
Opened 2016-09-02 06:19 UTC by chaithu14

2016-09-02 06:19 UTC, chaithu14 commented
@chinmaykolhatkar Please review and merge.

2016-10-05 06:17 UTC, chinmaykolhatkar requested changes
Please take care of comments as mentioned.

2016-10-05 06:17 UTC, chinmaykolhatkar commented on tutorials/README.md
> -
Why this removal of line?

2016-10-05 06:17 UTC, chinmaykolhatkar commented on tutorials/transform/src/main/java/com/example/transform/CustomerEvent.java
> +  public int customerId;
All the fields in tuple POJO should be private.

2016-10-05 06:17 UTC, chinmaykolhatkar commented on tutorials/transform/src/main/java/com/example/transform/CustomerInfo.java
> +  public int customerId;
All the fields should be private.

2016-10-05 06:17 UTC, chinmaykolhatkar commented on tutorials/transform/src/main/java/com/example/transform/Application.java
> +    dag.setAttribute(transform, Context.OperatorContext.PARTITIONER, new StatelessPartitioner<TransformOperator>(2));
Maybe also have an application showing Dynamic partitioning. Please add steps in document to show how to drive dynamic partitioning. You can use Throughput based partitioner for it.

2016-10-05 06:17 UTC, chinmaykolhatkar commented on tutorials/README.md
> +| transform         | Shows how to use the transform operator. |
"Shows how to use the transform operator" -> "Example for Transform Operator"

2016-10-05 06:19 UTC, chinmaykolhatkar commented
Also, did you run the applications in cluster mode?

2016-10-10 11:39 UTC, chaithu14 commented on tutorials/README.md
> +| transform         | Shows how to use the transform operator. |
Done.

2016-10-10 11:39 UTC, chaithu14 commented on tutorials/transform/src/main/java/com/example/transform/CustomerEvent.java
> +  public int customerId;
Done.

2016-10-10 11:39 UTC, chaithu14 commented
Incorporated the review comments.

2016-10-10 14:06 UTC, chinmaykolhatkar approved these changes

2016-10-10 14:06 UTC, merged