SPOI-8304: Cassandra Input operator example
DataTorrent/examples pull request #35
Opened 2016-09-28 12:02 UTC by DT-Priyanka

Application to showcase how to use cassandra input operator from Malhar.

2016-09-28 12:03 UTC, DT-Priyanka commented
@bhupeshchawda  please review.

2016-10-04 21:54 UTC, amberarrow commented
Parent directory README needs an entry

2016-10-04 21:56 UTC, amberarrow commented on tutorials/cassandraInput/README.md
> +    shell> mvn clean install
install => package

2016-10-05 05:23 UTC, bhupeshchawda requested changes

2016-10-05 05:23 UTC, bhupeshchawda commented on tutorials/cassandraInput/README.md
> +| dt.operator.CassandraReader.prop.store.node | cassandra server node |
Can you add a sample value for node? Is it just an IP?

2016-10-05 05:23 UTC, bhupeshchawda commented on tutorials/cassandraInput/src/test/java/com/datatorrent/cassandra/CassandraApplicationTest.java
> +        mapNames.put(i, "test" + i);
not using mapNames and mapAge?

2016-10-05 05:23 UTC, bhupeshchawda commented on tutorials/cassandraInput/src/test/java/com/datatorrent/cassandra/CassandraApplicationTest.java
> +      lc.run(10000); // runs for 10 seconds and quits
This will again run for 10 secs and end. Do this after you set the exit condition.

2016-10-12 10:15 UTC, DT-Priyanka commented on tutorials/cassandraInput/src/test/java/com/datatorrent/cassandra/CassandraApplicationTest.java
> +}
I tried using "cassandra-unit" embedded server. It seems difficult to use it as of now as there is no way to inject, cluster or session from outside. Also using mocks in functional/application test doesn't look like a good idea. I have already created a ticket to use embedded cassandra server in Malhar. Once we do that (that may involve some code changes like exposing some getter/setters etc.) we can write tests with embedded server in examples as well.

2016-10-12 10:26 UTC, DT-Priyanka commented
@bhupeshchawda  addressed review comments.

2016-10-12 11:09 UTC, bhupeshchawda commented
@DT-Priyanka Please address the comment by Ram - Add entry in tutorials/README.md for cassandra input app. 
Few unused variables in insertEventsInTable().
Added another comment for adding an assert() statement at the end.

2016-10-12 11:16 UTC, DT-Priyanka commented
done.

2016-10-12 11:40 UTC, bhupeshchawda approved these changes

2016-10-12 11:41 UTC, merged